import json
import logging
import os

def save_signal_output(data: dict, filename: str, folder: str = "output/signals"):
    """
    Saves the signal data to a JSON file.
    """
    try:
        os.makedirs(folder, exist_ok=True)
        filepath = os.path.join(folder, filename)
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=4)
        logging.info(f"Signal output saved to {filepath}")
    except Exception as e:
        logging.error(f"Error saving signal output: {e}")

def generate_markdown_report(ticker: str, signal_data: dict, insight: str, filename: str = None, folder: str = "output/reports"):
    """
    Generates a readable Markdown report.
    """
    if not filename:
        filename = f"{ticker}_report.md"
        
    try:
        os.makedirs(folder, exist_ok=True)
        filepath = os.path.join(folder, filename)
        
        content = f"""# Financial Insight Report: {ticker}

## Signal Summary
- **Action**: {signal_data.get('action', 'N/A')}
- **Confidence**: {signal_data.get('confidence', 0.0)}
- **Current Price**: {signal_data.get('current_price', 'N/A')}
- **Predicted Price (7d)**: {signal_data.get('predicted_price', 'N/A')}

## Key Reasons
{signal_data.get('reasons', 'N/A')}

## AI Analysis
{insight}

---
*Generated by Automated Financial Intelligence System*
"""
        with open(filepath, 'w') as f:
            f.write(content)
        logging.info(f"Markdown report saved to {filepath}")
        return filepath
    except Exception as e:
        logging.error(f"Error generating markdown report: {e}")
        return None
